
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[3]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[4]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[6]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[11]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[12]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[13]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[14]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[0]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[1]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[2]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[5]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[7]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[8]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[9]_i_1__0_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/s_input[10]_i_1__0_n_0}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/rf_reciever_wrapper_0/U0/inst_rf_reciever_wrapper/inst_rf_reciever/inst_iq_demod/inst_CIC_data_I/resize[7]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
